title: "NextFive"
logo: "images/logo.jpg" # You can add own logo image.
#baseurl: "/" # The subpath of your site, e.g. /blog
baseurl: "/thoughts" # The subpath of your site, e.g. /blog
# Uncomment to enable subscribe form
mailchimp: "" # put in your mailchimp audience list url
# Author Settings
author:
  name: Amit
  avatar: "images/logo.jpg"

# theme: hey-world
# remote_theme: hey-world
# Not having any permalink config here switches to default, 
#    generating links to posts at nextfive.xyz/yyyy/mm/dd/post.html while the actual pages are at nextfive.xyz/thoughts/yyyy/mm/dd/post.html
# permalink: /thoughts/:year/:month/:day/:title
# permalink: /thoughts/:title
