title: "Marcus Heng"
logo: "images/logo.jpg" # You can add own logo image.
baseurl: "/" # The subpath of your site, e.g. /blog
# Uncomment to enable subscribe form
; mailchimp: "" # put in your mailchimp audience list url
# Author Settings
author:
  name: Marcus Heng
  avatar: "images/logo.jpg"

theme: hey-world
