title: "NextFive"
logo: "images/logo.jpg" # You can add own logo image.
#baseurl: "/" # The subpath of your site, e.g. /blog
baseurl: "/thoughts" # The subpath of your site, e.g. /blog
# Uncomment to enable subscribe form
mailchimp: "" # put in your mailchimp audience list url
# Author Settings
author:
  name: Amit
  avatar: "images/logo-profile.jpg"

# theme: hey-world
# remote_theme: hey-world
# Leaving baseurl to "/thought" but Not having any permalink config here switches to default, 
#    generating links to posts at nextfive.xyz/yyyy/mm/dd/post.html while the actual pages are at nextfive.xyz/thoughts/yyyy/mm/dd/post.html
# permalink: /thoughts/:year/:month/:day/:title
# ------
# Setting baseurl to "/" but permalink to "/thoughts/:title" results in 
#     generating links to posts at nextfive.xyz/thoughts/post and actual page I cannot find
# ------
# Setting baseurl to "/thoughts" but permalink to "/:title" results in 
#     generating links to posts at nextfive.xyz/post and actual page at nextfive.xyz/thoughts/post
# ------
# Setting baseurl to "/thoughts" but permalink to "/thoughts/:title" results in 
#     generating links to posts at nextfive.xyz/thoughts/post and actual page I cannot find

permalink: /:title
